### ISSUE TITLE
Välipalautus 1

### ISSUE THREAD

**Issue by nikihietala** [taisteluvalmis/ANATOMY-for-dummies#1]
Todella selkeä readme.md, sain websovelluksen helposti toimimaan. Sovelluksen rakenne hyvä. Kirjautuminen toimii. Muut toiminnot vielä keskeneräisiä, joten ei voi vielä kommentoida. Tulevat toiminnot kuulostavat kuitenkin hyvin suunniteltuilta ja sopivilta.

**Comment by taisteluvalmis** [comment]
Kiitos palautteesta!
